[CmdletBinding()]
param([ValidateSet('Quick','Full')][string]$Profile='Full',[switch]$Enforce)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
$Repo=(Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path;$Manifest=Join-Path $env:LOCALAPPDATA 'ussmarines-security-tools\installed-tools.json'
if(-not(Test-Path $Manifest)){throw "Installe d'abord les outils depuis SpaceShooter-2D-web ou MailPerch: .\tools\security\install-security-tools.ps1"}
$Tools=(Get-Content -Raw $Manifest|ConvertFrom-Json).tools;$Reports=Join-Path $PSScriptRoot ('.reports\'+[DateTime]::UtcNow.ToString('yyyyMMdd-HHmmss'));New-Item -ItemType Directory -Force $Reports|Out-Null;$Failed=0
function Run([string]$Name,[scriptblock]$Command){Write-Host "[$Name] lancement..." -ForegroundColor Cyan;& $Command;if($LASTEXITCODE-ne 0){$script:Failed++;Write-Warning "[$Name] findings ou erreur; consulte le rapport."}else{Write-Host "[$Name] OK" -ForegroundColor Green}}
Push-Location $Repo
try{$Guard=@('.github/scripts/security_guard.py','--report',(Join-Path $Reports 'identity-guard.json'));if($Profile-eq'Full'){$Guard+='--history'};Run 'identity-guard' {& py -3 @Guard};$GL=@($(if($Profile-eq'Full'){'git'}else{'dir'}),'.','--redact=100','--exit-code=2','--report-format=json',("--report-path="+(Join-Path $Reports 'gitleaks.json')));if($Profile-eq'Full'){$GL+='--log-opts=--all'};Run 'gitleaks' {& $Tools.gitleaks.executable @GL};Run 'opengrep' {& $Tools.opengrep.executable scan --config '.security/opengrep/project-security.yml' --json-output (Join-Path $Reports 'opengrep.json') --error --exclude vendor --exclude node_modules --exclude dist --exclude coverage .};Run 'trivy' {& $Tools.trivy.executable filesystem --scanners vuln,misconfig --include-dev-deps --severity MEDIUM,HIGH,CRITICAL --format json --output (Join-Path $Reports 'trivy.json') --exit-code 1 .};& $Tools.trivy.executable filesystem --scanners vuln --include-dev-deps --format cyclonedx --output (Join-Path $Reports 'sbom.cdx.json') .;if(Test-Path package-lock.json){Run 'npm-audit' {& npm audit --audit-level=moderate --json 1> (Join-Path $Reports 'npm-audit.json')}};if(Test-Path composer.lock){$Composer=Get-Command composer -ErrorAction SilentlyContinue;if($Composer){Run 'composer-audit' {& $Composer.Source audit --locked --format=json 1> (Join-Path $Reports 'composer-audit.json')}}};Run 'zizmor' {& $Tools.zizmor.executable --offline --format json . 1> (Join-Path $Reports 'zizmor.json')}}finally{Pop-Location}
@{generatedAtUtc=[DateTime]::UtcNow.ToString('o');profile=$Profile;safeOutput=$true;matchedValuesIncluded=$false;failedChecks=$Failed}|ConvertTo-Json|Set-Content -Encoding UTF8 (Join-Path $Reports 'summary.json');Write-Host "Rapports: $Reports" -ForegroundColor Cyan;if($Enforce-and$Failed){exit 1};exit 0
